spring.application.name=ex03_jpa

#tomcat	설정
server.port=80

#datasource	(oracle)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=jpa
spring.datasource.password=jpa

#jpa	database - 이거 중요함
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#jpa - 이거 중요함
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
#처음에만 create해놓고 나중에는 update로 해놓으면 됨 아니면 도중에 다 drop될 수있으니 조심!!

#jpa	log - 이거 중요함
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=info
logging.pattern.console=[%d{HH:mm:ss}] %-5level %logger{36} - %msg%n