spring.application.name=ex04_security

#datasource (oracle)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr 

#mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.type-aliases-package=com.example.demo
mybatis.mapper-locations=classpath:mapper/**/*.xml

#log
logging.level.root=info
logging.level.com.example.demo=trace

logging.pattern.console= %-5level %logger{20} - [%L]%msg%n

spring.messages.basename=message
spring.messages.encoding=UTF-8

#파일 저장경로 출력하는 방법
file.upload = c:/uplaoad

# trace 포함 여부
server.error.include-stacktrace=on_param
